language: c
compiler: gcc
dist: xenial

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

env:
  - MODULE_NAME=redisgraph
  - REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/libmodule.so
  - REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server

before_script:
  - pip install --user redis ramp-packer rmtest
  - git clone -b 4.0.1 --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - cd ..

script:
  - cmake --version
  - cmake .
  - make clean
  - make module
  - cd src
  - mkdir -p ../build
  - module_packer -v -o "../build/redisgraph.{os}-{architecture}.latest.zip" "`pwd`/libmodule.so"
  - cd ..
  # - make test

deploy:
  # Module latest artifact
  - provider: s3
    access_key_id: AKIAJV5TLHJABHC5XH7A
    secret_access_key:
      secure: E9CY1H82Gt0SHw7IyhFiGYSvL+qnuPyTXKksLzVTpg8c83C2MFJwAMXOhW4JPLaSD/u7xZTSU9/DDLb6yEkbGvoKS2VMmuLKJDT13mRp4hV8jJnn3kb0sV6/7zq5d1qrKHkHd0VpTBybPuHRwHnO74mYOKx4XW6bDGsRMmCHljg4tRKU0gvGI+uvyO+iRvyj83o/erte/3QQXDIMsY7D/hvWRLnHg8Np0l1XC0F5nnKxuQlM/BtaQj06/xSy56QFDTiG51uZIfE5v5KiaA5V7Fde7SzdrRxMjKlRSI0u2LRhxepm3wfb+47R18sPE5kNMIq7v3licqjeEvR7piZf2p1TG3DX0heX4yxJkTxirpAuU95Wyu1VkivGBdhwwzI4bU4rZFDIrPJ9rQPX1eli//2s/6n1zS46+qHC2jQEIQ5Sj3ihuEVueV2CD+8OBS1yf+nfI7NT9OxToyDhhitMB5bNHOy+D3Su5IqHprn0B7pnXVto5iqYCnP+L6q2dyNkLX8E9sS1S2GToobSyVj69YEAP0bhq8k05ujq2canouJofraCYsWFNYvrsNkuaEaR4XwnaESg2+XnsPZBvJ2PCWby/HtSR7xAeR/Eqb2i2P8rBWrcNwxubT44q+hEa0iRDLylHVt/aKVrAxWP3WjuRF3VI5LBT1fxxbS4saAUa9o=
    skip_cleanup: true
    acl: public_read
    bucket: redismodules
    upload-dir: redisgraph
    on:
      branch: master
    local_dir: $TRAVIS_BUILD_DIR/build
